### PR TITLE
fix: compare only <owner>/<repo> when checking for rename

### LINKED ISSUE #885: Seeing EMISMATCHGITHUBURL from the latest version which breaks our release build
The latest version with the change: https://github.com/semantic-release/github/pull/878 is currently breaking our release build. We are using Travis CI to trigger our release build and we start to get `EMISMATCHGITHUBURL` even though our repository URL did not change. We are using Enterprise GitHub. Is there a way to show what is mismatching? We currently need to pin to version 10.1.1 to get our builds to work again.

### PR DESCRIPTION
**Pull request by jedwards1211**
This PR re-attempts the implementation made in #878 and reverted in #887, by staging a check in the plugin `verifyConditions` lifecycle using the `owner/repo` as opposed to the initial implementation where the `context.options.repositoryUrl` is compared against the fetched repo `clone_url`.

Related to #885 

### Screencast

**Error Demo**

https://github.com/user-attachments/assets/afb97b36-cd02-444d-8189-8474879b5a2d

**Success Demo**

https://github.com/user-attachments/assets/ea36ce68-71f6-41b7-82d3-6f657f9b534a

### CODE REVIEW

File: lib/verify.js [hunk 1]
```diff
@@ -166,7 +166,15 @@ export default async function verify(pluginConfig, context, { Octokit }) {
       status,
       data: { clone_url },
     } = await octokit.request("GET /repos/{owner}/{repo}", { owner, repo });
-    if (status !== 200 || repositoryUrl !== clone_url) {
+
+    // compare only the <owner>/<repo> part of the two URLs in case one URL is HTTPS
+    // and the other is SSH
+    const getRepoPath = url => new URL(url).pathname.replace(/\.git$/, '')
```
Comment (babblebey) [inline lib/verify.js:172]: We already have a utility function that you can use in place of this `parseGitHubUrl`... see https://github.com/semantic-release/github/blob/master/lib/parse-github-url.js

File: lib/verify.js [hunk 2]
```diff
@@ -166,7 +166,15 @@ export default async function verify(pluginConfig, context, { Octokit }) {
       status,
       data: { clone_url },
```
Comment (babblebey) [inline lib/verify.js:167]: Also, maybe we could just use the `git_url` property instead at this point 😉

**Review by babblebey — CHANGES_REQUESTED** [review]
Great stuff @jedwards1211,

Do rake a look at the bit of nits and kindly address the conflict for now... We are looking to add some tests too... We'll look at how to go about that after this.

**Comment by jedwards1211** [comment]
@babblebey okay I made those changes and included the current `repositoryUrl` and `git_url` values in the error message.

There are unrelated formatting changes in here now -- is your CI not enforcing the code formatting, or did the formatting settings change?

**Comment by jedwards1211** [comment]
Okay I opened this issue: #890

**Comment by babblebey** [comment]
Run `npm run lint:prettier:fix`

**Comment by jedwards1211** [comment]
sorry for the noise, `vscode-prettier`'s fault

**Comment by jedwards1211** [comment]
@babblebey okay I added tests.  I also noticed that the repo rename check was being skipped if running in a GitHub action, and that it was making a redundant request for the repo information.  I was able to move things around to eliminate the redundant request, and check for rename even if running in a GitHub action.

File: test/integration.test.js [hunk 3]
```diff
@@ -426,9 +444,10 @@ test("Comment and add labels on PR included in the releases", async (t) => {
       {
         permissions: { push: true },
         full_name: `${owner}/${repo}`,
+        git_url: `htttps://api.github.local/${owner}/${repo}.git`,
       },
       {
-        // TODO: why do we call the same endpoint twice?
+        // TODO: why do we call the same endpoint three times?
```
Comment (babblebey) [inline test/integration.test.js:450]:
```suggestion
```

Please remove the comment at this point 😉, the question is already answered haha 😃

Comment (jedwards1211) [reply test/integration.test.js:450]: well, `GET /repos/${owner}/${repo}` still gets called twice in many tests for some other reason

Comment (jedwards1211) [reply test/integration.test.js:450]: confirmed, `fail.js` and `success.js` do `GET /repos/{owner}/{repo}`

Comment (jedwards1211) [reply test/integration.test.js]: anyway I did remove the comment

**Comment by jedwards1211** [comment]
Nice testing setup y'all!  I like the thoroughness of the GitHub mocking, and also the fact that you aren't using Jest lol

**Comment by jedwards1211** [comment]
@babblebey anything else y'all need on this?

File: test/success.test.js [hunk 4]
```diff
@@ -2269,6 +2288,7 @@ test('Skip closing issues if "failComment" is "false"', async (t) => {
     .sandbox()
     .getOnce(`https://api.github.local/repos/${owner}/${repo}`, {
       full_name: `${owner}/${repo}`,
+      git_url: `https://api.github.local/${owner}/${repo}.git`,
```
Comment (babblebey) [inline test/success.test.js:2291]: Let's write a test case where the `git_url` is 

- without `https`
- with `ssh`
- ...and any other format of `git_url` possible.

**Review by babblebey — CHANGES_REQUESTED** [review]
Hey @jedwards1211 😁,

I gave this a whirl 😉, changes looks great 👍.... and thank you for sticking to this. I have also gone on and written a description for the PR.

In order to fulfil the test coverage requirement mentioned in the reverted PR #887. Please take a look at the review comment.

File: test/success.test.js (hunk 4 above)
Comment (jedwards1211) [reply test/success.test.js:2291]: okay, I think I should put those tests in `verify.test.js` though, this comment is in `success.test.js` but the success step doesn't do anything with `git_url`

Comment (jedwards1211) [reply test/success.test.js:2291]: @babblebey you know, I think we should go back to `clone_url`.  There are two issues I see with `git_url`:
- It's always `git://` protocol, but GH docs say you can only push to HTTPS or SSH URLs.  (the git protocol has no authentication).  Not that it really makes a difference, but `clone_url` is HTTPS, and there's always `ssh_url`.
- The example for `git_url` in GH docs is `git:github.com/octocat/Hello-World.git`, which isn't a valid URL.  The api seems to always return `git://`, but this just makes me feel more wary of that field...

Comment (babblebey) [reply test/success.test.js:2291]: > you know, I think we should go back to clone_url, or ssh_url. 

Let's do it @jedwards1211 ✊🏾

We must only ensure we have a test covering all the possible formats of the `clone_url`... I found this, maybe it can help 🙂

https://git-scm.com/docs/git-clone/en#_git_urls

Comment (babblebey) [reply test/success.test.js:2291]: > I'm pretty sure clone_url is always HTTPS (it doesn't seem like any of these fields can vary in their format)

Though I think there could be more format eh, varying from `http`, `https`, to `ssh`, `git` (itself) and even `ftp`....referring to the git docs https://git-scm.com/docs/git-clone/en#_git_urls

....and considering your comment https://github.com/semantic-release/github/issues/885#issuecomment-2251402572 where I see an `ssh` looking kind of `clone_url`

🤔

Comment (jedwards1211) [reply test/success.test.js:2291]: Oh well yes, git itself accepts many different URL formats, but GitHub is in control of what clone_url it returns, so I think it always uses the same format.  But I'll double check if there's any way for users to configure the clone_url format.

The ssh-like URLs in my comment on #885 didn't come from the GitHub API, but rather, when I tried to `git remote set-url` with a normal HTTPS URL, for some reason git stored a more SSH style URL instead.  So if you want me to test the weird URL formats stored in git remotes then I should set `repositoryUrl` to the weird formats in the tests, rather than `clone_url` or `git_url`.

Comment (babblebey) [reply test/success.test.js:2291]: > So if you want me to test the weird URL formats stored in git remotes then I should set `repositoryUrl` to the weird formats, rather than `clone_url` or `git_url`.

Oh no 😃, the `repositoryUrl` cannot be the weird format, this is because the `repositoryUrl` is the already parsed url gotten of the project from either its `package.json` or semantic-realease config.

It is the value we're trying to verify to confirm whether its correct/updated by fetching repo data... main reason for this PR 😉

Comment (jedwards1211) [reply test/success.test.js:2291]: What I mean is the sematic-release docs say for `repositoryUrl`:
> Any valid git url format is supported

So there are a lot of options for what users could configure it to.

Have you seen an example of the GitHub API returning a `clone_url` that isn't in HTTPS format?

Comment (jedwards1211) [reply test/success.test.js]: Okay I switched back to `clone_url` and make the tests go through a matrix of possible combinations for `clone_url` and `repositoryUrl` formats.

Comment (babblebey) [reply test/success.test.js]: > make the tests go through a matrix of possible combinations for `clone_url` and `repositoryUrl` formats.

Haha 😆 

Well, there's literally a matrix possible format of `repositoryUrl` any way, considering that depends on the format configured for `semantic-release` per project yea... and maybe same for `clone_url`... But the thing that matters most in there is the `owner/repo` 😉

Comment (jedwards1211) [reply test/success.test.js]: Yup.  Let me know if I need to do anything else on this

**Comment by babblebey** [comment]
This is great stuff right here @jedwards1211. I commend you for sticking to this yea. 

I have given another whirl and added a video demo of my testing to the PR Description (reviewers like that stuff 😉).

**Comment by jedwards1211** [comment]
nice, thank you!

**Review by babblebey — APPROVED** [review]
🚀
