### PR TITLE
fix: use retry and throttle octokit plugins

### LINKED ISSUE #299: replace custom throttling code with @octokit/plugin-throttling
as part of that, enable testing in Mac OS and Windows which currently fail because of flaky tests of the throttling code:
https://github.com/semantic-release/github/pull/298/checks?check_run_id=1397908452

### PR DESCRIPTION
**Pull request by achingbrain**
Refactors the client to use [@octokit/plugin-retry](https://www.npmjs.com/package/@octokit/plugin-retry) and [@octokit/plugin-throttling](https://www.npmjs.com/package/@octokit/plugin-throttling) as GitHub occasionally changes it's API and these plugins can abstract those changes away from this module.

- Removes `lib/definitions/rate-limit.js`
- Adds `lib/definitions/retry.js` and `lib/definitions/throttle.js` to handle retry/throttle settings
- Updates tests to be more like GitHub (returing the correct rate limit response headers, etc)

Fixes #299 and https://github.com/semantic-release/semantic-release/issues/2204
See also #480 and #378

### CODE REVIEW

**Comment by lapastillaroja** [comment]
It would be great if this PR can be reviewed and marged. I'm facing same problem in one of my projects

**Comment by rathpc** [comment]
Would love to get this reviewed and merged!! Can we update to resolve conflicts and tag some people for review?

**Comment by achingbrain** [comment]
Conflicts are gone, not sure who would review - @travi @gr2m ?

**Comment by gr2m** [comment]
I'm still on parental leave, and first week back to work will be busy, but I have it on my radar

**Comment by PocketlawErik** [comment]
@gr2m Wonderful to hear!

Running into this same problem right now. All your hard work is much appreciated! Thanks!

Please let me know if there is anything I can do to help 🙏❤️

**Comment by xorph** [comment]
@gr2m Any ETA for a review of this PR? We have to deal a lot with the secondary rate limits in our release process lately.

**Comment by stipsan** [comment]
Hi @gr2m, our usage of `semantic-release` at [sanity.io](https://www.sanity.io/) is only increasing as it's [such a boost to our productivity](https://github.com/sanity-io/semantic-release-preset).

We're also impacted by this problem now and then, is there a way we can help @gr2m?
Either by reviewing and fixing things adjacent to ESM or would you prefer us to join the effort to land ESM #418? We've been doing a [lot](https://github.com/sanity-io/get-it/pull/25) [of](https://www.sanity.io/blog/sanity-studio-v3-developer-preview#e44ae09ffa62:~:text=the%20packages%20to-,ECMAScript%20Modules%20(ESM),-with%20CommonJS%20fallback) [ESM](https://github.com/sanity-io/client/pull/29) migrations in our own projects this year so it's familiar grounds to us 🥲

**Comment by achingbrain** [comment]
@travi @gr2m is there any chance you could find some time to review this PR?  I've updated it to resolve the recent conflicts, it solves a very real problem when using this module in monorepos that publish lots of modules in one go.

Please let me know if there's anything I can do to help you get it across the line?

**Comment by rlch** [comment]
+1 -- we constantly run into rate-limiting issues in our delivery workflows. Getting quite tedious having to constantly monitor and manually retry failed actions.

**Comment by rathpc** [comment]
sorry for pinging directly but we really need traction on this PR to get it merged. It has been 8 months already and this issue is plaguing many people.

Can one of you review and get this merged please? @boennemann @gr2m @kbrandwijk @keplersj @pvdlg @travi @UziTech

**Review by Nargonath — COMMENTED** [review]
I'm no semantic-release expert but the rest LGTM

**Review by UziTech — APPROVED** [review]
LGTM

**Review by Nargonath — APPROVED** [review]

**Comment by Aeolun** [comment]
If nobody currently working on this project has time to review/merge these changes, is there a chance someone else can get review/merge permissions? 8 months for a PR that looks fairly straightforward (and presumably passes tests) is a bit much.

**Comment by rathpc** [comment]
another 2 weeks bites the dust and another 30 or so failures I have experienced due to this secondary rate limit issue.

What can we do to get this merged and released please?

**Comment by tractorcow** [comment]
Thanks @achingbrain I'm using this in my github action and it seems to work well (will report if I run into any rate limiting issues).

```
npm install -g \
          @semantic-release/github@npm:@achingbrain/semantic-release-github@0.0.1 \
          semantic-release \
          @semantic-release/exec \
          @semantic-release/git
```

**Comment by tractorcow** [comment]
Looks like I spoke too soon. I have the issue even with the suggested fork. However, even with retry and delay rate limit errors are still possible.


```
[1:55:15 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
(node:1886) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[1:55:16 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/pixelfusion/mindlab-wl-academyex-website/releases/tag/v1.20.0-uat.39
[1:55:16 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[1:55:16 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[1:55:16 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[1:55:16 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[1:55:17 AM] [semantic-release] › ✘  Failed step "success" of plugin "@semantic-release/github"
[1:55:17 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[1:55:17 AM] [semantic-release] [@semantic-release/exec] › ℹ  Call script echo 'v1.20.0-uat.39' > version.txt
[1:55:17 AM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[1:55:17 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.
    at /opt/hostedtoolcache/node/18.12.1/x64/lib/node_modules/semantic-release/node_modules/@octokit/request/dist-node/index.js:88:21
```

**Comment by tractorcow** [comment]
@achingbrain is there an issue with the way I'm deploying your fix, or is the fix legitimately not catching the rate limiting?

**Comment by carlobernardini** [comment]
Respectfully, is this project still maintained? This pr has been open for almost a year, the last merge is of a similar date. It would be really great if we can get this merged since the issue is hurting many.

**Comment by achingbrain** [comment]
@tractorcow you can see how I'm using the plugin [here](https://github.com/ipfs/aegir/blob/master/package.json#L231).  

Unfortunately there are still [some](https://github.com/octokit/plugin-throttling.js/issues/566) [bugs](https://github.com/octokit/plugin-throttling.js/issues/454) in the throttle plugin itself, though those will be fixed there and not here.

**Comment by tractorcow** [comment]
Thanks for getting back to me.

For now i'm using `semantic-release || true` in my release scripts, because even if github fails, my code still gets deployed in that case anyway :)

**Comment by alexsanderp** [comment]
News?

**Comment by RyKilleen** [comment]
For what it's worth, this challenge is the one blocker for adoption, both for me and the organizations I work with.

I think semantic release is such a great tool, being able to use it without the friction of half failed releases in the GH Actions would be awesome!

**Comment by JeanGautierSherpas** [comment]
Hello, 
Big fan of semantic-release, I used it every where in project i worked for.
This is issue is causing trouble for my current organisation, is it possible to accelerate solving ?
Need any hand ?

File: lib/definitions/retry.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/**
+ * Default exponential backoff configuration for retries.
+ */
+const RETRY_CONF = {
+  retries: 3,
+  retryAfterBaseValue: 1000,
+  doNotRetry: [400, 401, 403],
```
Comment (johanneswuerbach) [inline lib/definitions/retry.js:7]: After switching to your branch (thanks for that) we still see rate-limits, but they always seem to return with a 403.

Any reason why 403s where excluded?

image

Comment (tractorcow) [reply lib/definitions/retry.js:7]: Yes, maybe that's the issue I ran into. I noticed that rate limiting wasn't retrying.

**Comment by gr2m** [comment]
I will prioritize this issue once we ship the ESM updates. I'll plan on working on this after April 14th

File: lib/definitions/retry.js (hunk 1 above)
Comment (johanneswuerbach) [reply lib/definitions/retry.js:7]: Nor sure if you still use the instruction provided in https://github.com/semantic-release/github/pull/487#issuecomment-1377986211, but for us it started to work after actually defining an override in our `package.json`:

```
"overrides": {
    "semantic-release": {
      "@semantic-release/github": "$@semantic-release/github"
    }
}
```

**Comment by rebeljoi** [comment]
For those of you who still experience this problem. I solved this in the meantime by disabling the features in the `@semantic-release/github` plugin that uses the `https://api.github.com/search` endpoint, which is the one that causes the `secondary rate limit exceeds`.

Configure `@semantic-release/github` as follows:
```
[
  "@semantic-release/github",
  {
    "successComment": false,
    "failTitle": false
  }
]
```

File: lib/definitions/retry.js (hunk 1 above)
Comment (achingbrain) [reply lib/definitions/retry.js:7]: I believe the secondary rate limit error is caused by this: https://github.com/octokit/plugin-throttling.js/issues/454

This may be a short-term solution - https://github.com/semantic-release/github/pull/487#issuecomment-1486298997 but I think it'll turn off the (rather nice) feature that adds a comment to each PR in a given release saying "this PR is included in release version XXX"

**Comment by achingbrain** [comment]
Godspeed @gr2m and massive ❤️ for picking this up again, it's a vital part of so many people's workflows.

I've noticed a lot of people are linking to this PR saying it will solve the rate limiting problems - they should know it's only part of the solution, https://github.com/octokit/plugin-throttling.js/issues/454 needs addressing too.

**Comment by gr2m** [comment]
Okay more like May 12 but that's how life goes sometimes. Thank you all for your patience and your help. I'm looking into it now

**Comment by gr2m** [comment]
It's happening dot gif

If I had more time I'd add tests for `lib/semantic-release-octokit.js` but it's a tad complicated if we make it right, and tests will change in the upcoming ESM version, so chose to ... not.

I'm looking into the failing Node 14.17 tests. If y'all could give the latest version a try, I'd be much obliged

File: lib/definitions/retry.js [hunk 2]
```diff
@@ -2,9 +2,9 @@
  * Default exponential backoff configuration for retries.
  */
 const RETRY_CONF = {
-  retries: 3,
-  retryAfterBaseValue: 1000,
```
Comment (gr2m) [inline lib/definitions/retry.js]: these are [default values already set in Octokit](https://github.com/octokit/plugin-retry.js/blob/7dc13d95447c1828eea1f173a635289872d3b1bd/src/index.ts#L12-L15).

**Review by travi — APPROVED** [review]

**Comment by gr2m** [comment]
I published the current version as `@gr2m/semantic-release-github-487@0.0.0-development` for easier testing.

You can use aliasing to test it out. In your package.json

```js
  "devDependencies": {
    "semantic-release": "^21.0.2",
    "@semantic-release/github": "npm:@gr2m/semantic-release-github-487@0.0.0-development"
  },
```

**Comment by gr2m** [comment]
Alright I tested it some, it's Saturday, let's give this a go. I'm confident in this not introducing any new problems, but we can really only see once it's used out there.

**Comment by gr2m** [comment]
We want to thank you all for your patience and support, really 💐❤️
