### PR TITLE
fix: replace github search api with graphql in success lifecycle method

### LINKED ISSUE #644: API rate limit exceeded for installation
I was hoping that rate limiting is now properly taken care of since we moved to Ocotkit via https://github.com/semantic-release/github/pull/487, but the error popped up again

https://github.com/semantic-release/commit-analyzer/actions/runs/5159013164/jobs/9293389281#step:6:126

We can tell from the user agent that the correct `@semantic-release/github` version was used

```
      'user-agent': '@semantic-release/github v8.1.0 octokit-core.js/4.2.1 Node.js/18.16.0 (linux; x64)',
```

What's odd: the `request` option does not have a `retries` key, it looks like it didn't attempt to retry at all:
https://github.com/semantic-release/commit-analyzer/actions/runs/5159013164/jobs/9293389281#step:6:138

I will look into it. Sorry, I'm not sure why this is happening and rate limit errors are hard to reproduce reliably, it will take me a moment to get to the bottom of this. If anyone is inclined to help out, you are very welcome to

### PR DESCRIPTION
**Pull request by babblebey**
This Pull Request refactors the `success` lifecycle function replacing the usage of Github "Search API" with "GraphQL API".

#### Changes Made

- Added `buildAssociatedPRsQuery` helper function to which builds GraphQL query for fetching associated PRs to a list of commit hash (sha). It does this by collecting a list of `shas` which maps down to a list of strings that leverages the GraphQL `fragment` enabling ability to request data of multiple commits in one request using `GitObject`. 

    ```js
    /**
     * Builds GraphQL query for fetching associated PRs to a list of commit hash (sha)
     * @param {Array<string>} shas
     * @returns {string}
     */
    export function buildAssociatedPRsQuery(shas) {
      return `#graphql
        query getAssociatedPRs($owner: String!, $repo: String!) {
          repository(owner: $owner, name: $repo) {
            ${shas
              .map((sha) => {
                return `commit${sha.slice(0, 6)}: object(oid: "${sha}") {
                ...on Commit {
                  associatedPullRequests(first: 100) {
                    nodes {
                      url
                      number
                      body
                    }
                  }
                }
              }`;
              })
              .join("")}
          }
        }
      `;
    }
    ```
- Replaced the instance of the search api consumption with the `getSearchQueries` method integration with the graphql api integration, which was used to retrieve all associated pull requests.

    ```js
    const { repository } = await octokit.graphql(
      buildAssociatedPRsQuery(shas),
      { owner, repo },
    );
    const associatedPRs = Object.values(repository).map(
      (item) => item.associatedPullRequests.nodes,
    );
    ```
- Modified test suites in acknowledgement of the changes..

### Related Issue

Fixes #644

### Screencast/Screenshot

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.06.24-14_54_49.webm](https://github.com/semantic-release/github/assets/25631971/0135e31b-baa2-436c-b4e1-9abddffc60e5)

### CODE REVIEW

File: lib/success.js [hunk 1]
```diff
@@ -65,21 +65,81 @@ export default async function success(pluginConfig, context, { Octokit }) {
...
+                    url
+                    number
+                  }
+                }
+              }
+            }`
+          }).join("")}
+        }
+      }
+    `;
```
Comment (babblebey) [inline lib/success.js:85]: I figured that query out 😉

File: lib/success.js [hunk 2]
```diff
@@ -65,21 +65,81 @@ export default async function success(pluginConfig, context, { Octokit }) {
...
+    //   }
+    // };
+    // console.log(somedata)
 
-    const searchQueriesResults = await Promise.all(searchQueries);
-    const uniqueSearchQueriesResults = uniqBy(
-      flatten(searchQueriesResults),
+    const { data } = await octokit.graphql(loadAssociatedPRsQuery(shas), { owner, repo });
+    
+    const associatedPRs = toArray(mockReponse.data.repository).map((item) => item.associatedPullRequests.nodes);
```
Comment (babblebey) [inline lib/success.js:116]: Following the the GQL query run which (consumes the `loadAssociatedPRsQuery`), the deduced data `associatedPRs` is exactly structurally like the commented out `searchQueriesResults` data above there.

**Review by babblebey — COMMENTED** [review]
I'm pretty sure this works, but can't exactly test, hence I've got to figure how to update the test for a mock .... This is where i'm kinda BLOCKED..

See the comments associated to this review first.... then hear my **BLOCKER** 😉 

I notice the convention with the usage of the `fetch-mock`'s `sandbox().getOnce()` method which mocks a request and provides a response to an api, but my question is...

**HOW EXACTLY DO I MOCK THE GRAPHQL ENDPOINT??? using similar convention 🤔 ** 

I'm not sleeping on it too 😉

**Comment by gr2m** [comment]
> requires some new dependencies

you don't need the `@octokit/graphql` dependency to mock graphql requests, you just mock the `POST /graphql` request like any other.

File: lib/success.js [hunk 3]
```diff
@@ -250,3 +291,24 @@ export default async function success(pluginConfig, context, { Octokit }) {
     throw new AggregateError(errors);
   }
 }
+
+export function loadAssociatedPRsQuery (shas) {
```
Comment (gr2m) [inline lib/success.js:295]: there is no loading happening here, I'd call it something like 

```suggestion
export function buildAssociatedPRsQuery (shas) {
```

File: lib/success.js [hunk 4]
```diff
@@ -250,3 +291,24 @@ export default async function success(pluginConfig, context, { Octokit }) {
...
+  return `#graphql
+    query getAssociatedPRs($owner: String!, $repo: String!) {
+      repository(owner: $owner, name: $repo) {
+        ${shas.map((sha) => {
+          return `"${sha.slice(0, 6)}": object(oid: ${sha}) {
```
Comment (gr2m) [inline lib/success.js:300]: node aliases have to begin with a letter, but most shas begin with a number

```suggestion
          return `"commit${sha.slice(0, 6)}": object(oid: ${sha}) {
```

File: lib/success.js [hunk 5]
```diff
@@ -65,21 +65,62 @@ export default async function success(pluginConfig, context, { Octokit }) {
...
+    //         }
+    //       }
+    //     }
+    //   }
+    // };
+    // console.log(somedata)
+
+    const { data } = await octokit.graphql(loadAssociatedPRsQuery(shas), { owner, repo });
+    
+    const associatedPRs = toArray(mockReponse.data.repository).map((item) => item.associatedPullRequests.nodes);
```
Comment (gr2m) [inline lib/success.js:97]: is `toArray` doing the same as [`Object.values()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values) here?

Comment (babblebey) [reply lib/success.js:97]: Yea, I found `toArray` to be more easy to read... Plus I didn't even think of `object.values`, as we've already established usage of `lodash`.

Comment (gr2m) [reply lib/success.js:97]: In general, prefer native APIs over modules. We use lodash for legacy reasons but over time we might get rid of it as the need for it declines.

**Comment by gr2m** [comment]
Holler if you need help with this PR

File: lib/success.js (hunk 5 above)
Comment (babblebey) [reply lib/success.js]: True 😉

File: lib/get-search-queries.js
Comment (gr2m) [inline lib/get-search-queries.js:1]: let's delete that file altogether

**Review by gr2m — COMMENTED** [review]
Yoooo!! Awesome PR, can't wait to give this a go! I've to run now but might get to it later tonight! Great work 💐

**Comment by gr2m** [comment]
I ran it locally and got the following error

```
[8:46:26 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[8:46:27 PM] [semantic-release] › ✘  Failed step "success" of plugin "@semantic-release/github"
[8:46:27 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Parse error on "commit338966" (STRING) at [4, 9]
    at file:///Users/gr2m/code/semantic-release/semantic-release/node_modules/aggregate-error/index.js:23:26
    at Array.map (<anonymous>)
    at new AggregateError (file:///Users/gr2m/code/semantic-release/semantic-release/node_modules/aggregate-error/index.js:16:19)
    at file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as success] (file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:218:3)
    at async Module.default (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:278:22)
    at async default (file:///Users/gr2m/code/semantic-release/semantic-release/cli.js:55:5) {
  locations: [ { line: 4, column: 9 } ],
  pluginName: '@semantic-release/github'
}
AggregateError: 
    Error: Parse error on "commit338966" (STRING) at [4, 9]
        at Array.map (<anonymous>)
        at file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/pipeline.js:55:13
        at async pluginsConfigAccumulator.<computed> [as success] (file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/index.js:87:11)
        at async run (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:218:3)
        at async Module.default (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:278:22)
        at async default (file:///Users/gr2m/code/semantic-release/semantic-release/cli.js:55:5)
    at file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as success] (file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:218:3)
    at async Module.default (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:278:22)
    at async default (file:///Users/gr2m/code/semantic-release/semantic-release/cli.js:55:5) {
  errors: [
    Error: Parse error on "commit338966" (STRING) at [4, 9]
        at file:///Users/gr2m/code/semantic-release/semantic-release/node_modules/aggregate-error/index.js:23:26
        at Array.map (<anonymous>)
        at new AggregateError (file:///Users/gr2m/code/semantic-release/semantic-release/node_modules/aggregate-error/index.js:16:19)
        at file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/pipeline.js:55:13
        at async pluginsConfigAccumulator.<computed> [as success] (file:///Users/gr2m/code/semantic-release/semantic-release/lib/plugins/index.js:87:11)
        at async run (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:218:3)
        at async Module.default (file:///Users/gr2m/code/semantic-release/semantic-release/index.js:278:22)
        at async default (file:///Users/gr2m/code/semantic-release/semantic-release/cli.js:55:5) {
      locations: [Array],
      pluginName: '@semantic-release/github'
    }
  ]
```

In order to run it locally, checkout the `semantic-release/semantic-release` repo and the `semantic-release/github` repo. Run `npm install in both`. Then in the `semantic-release` folder, run `npm install <relative path to the github folder>` (e.g. in my case on Mac OS, the folders are next to each other, I ran `npm install ../github`. 

The way I ran it locally is as follows

1. Create a test repository with a package.json, set `"version": "0.0.0-development"`
2. check it out locally
3. Add a commit with `feat: initial version` or similar (`git commit --allow-empty -m 'feat: initial version'`)
4. Make sure you are signed out of `npm` locally (run `npm logout`)
5. Create a classic automation token on npm (https://www.npmjs.com/settings/<your npm username>/tokens/`)
6. Create a personal access token with the `repo` scope
7. Set the following environment variables

   ```
   CI=true
   GITHUB_ACTIONS=true
   GITHUB_REF=master
   GITHUB_SHA=<latest commit sha>
   GITHUB_RUN_ID=1
   GITHUB_REPOSITORY=<your full repository name (owner/repo)>
   GITHUB_WORKSPACE=<path to current folder>
   NPM_TOKEN=<your npm token>
   GITHUB_TOKEN=<your github token>
   ```

8. Run the following command in your local clone of the test repository

   ```
   <path to semantic-release folder>/bin/semantic-release.js
   ```

Not sure if this could be streamlined ... but we should document it somewhere for future reference and improve if we can 😁

**Comment by gr2m** [comment]
It's possible that this error is an edge case that only happens because I ran it locally. The commit only exist on my machine due to the local testing. When your query is sent, the commit does not exist and probably returns null or even an error. If that happens, I'd simply ignore the commit and move on to the next one

File: lib/get-search-queries.js
Comment (babblebey) [reply lib/get-search-queries.js:1]: :checkmark:

**Comment by babblebey** [comment]
> It's possible that this error is an edge case that only happens because I ran it locally. The commit only exist on my machine due to the local testing. When your query is sent, the commit does not exist and probably returns null or even an error. If that happens, I'd simply ignore the commit and move on to the next one

@gr2m, I figured it was a GraphQL error... turned out I had a some part of the query returned string (from the `buildAssociatedPRsQuery`) wrongly typed... i.e. the `alias text` and the `oid`.

**Comment by gr2m** [comment]
Great work! I'd like to see that the success step actually posts a comment, we can pair on it during our checkin today

File: lib/success.js [hunk 6]
```diff
@@ -250,3 +243,32 @@ export default async function success(pluginConfig, context, { Octokit }) {
...
+                  number
+                  body
+                }
+              }
+            }
+          }`;
+          })
+          .join("")}
+      }
+    }
```
Comment (gr2m) [inline lib/success.js:272]: We will need to address the possibility that there might be more than 100 commits. If that occurs, we need to send multiple requests as only 100 nodes can be requested with a single GraphQL request

**Review by gr2m — APPROVED** [review]
Let's goo 🚀

**Comment by gr2m** [comment]
How fitting that the release of this fix also ran into the secondary rate limit issue:
https://github.com/semantic-release/github/actions/runs/9748385825/job/26903265854
(but that was still using the old code though)

**Comment by babblebey** [comment]
> (but that was still using the old code though)

I sigh in relief**** 😮‍💨

File: lib/success.js (hunk 6 above)
Comment (brandon-kyle-bailey) [reply lib/success.js:272]: was this addressed in this PR? im working with a repo that has more than 100 commits and am experiencing this secondary rate error on v24.0.0

Comment (babblebey) [reply lib/success.js:272]: Hey @brandon-kyle-bailey

The Edge Case isn't addressed in this PR nor yet.

But, could you kindly open an issue with details of this error you're getting in regard this 100+ commit, thanks.

Comment (brandon-kyle-bailey) [reply lib/success.js:272]: unfortunately this is happening on an internal repo but ill do my best! @babblebey

Comment (brandon-kyle-bailey) [reply lib/success.js:272]: @babblebey im not able to reliable reproduce it at this point since re-running so will hold off on logging an issue. will revisit if it reappears!

Comment (babblebey) [reply lib/success.js:272]: I'm currently working on a fix in regard the edge case here #892

Comment (babblebey) [reply lib/success.js:272]: I'm currently working on a fix in regard the edge case here #892

Comment (travi) [reply lib/success.js:272]: just capturing the relation to https://github.com/semantic-release/github/issues/867#issuecomment-2265881923 as well
