### PR TITLE
fix: replace `searchAPI` usage with `GraphQL` in `findSRIssue` util

### LINKED ISSUE #867: Exceeding a secondary rate limit even with 10.0.7
Hey there, I saw that a recent release was made to use GraphQL instead of Github's API to avoid hitting the rate limits.
I bumped my `@semantic-release/github` version to use `^10.0.7` but even with this, I'm hitting the limits:

```
 AggregateError: 
    HttpError: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID XXX. - https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits
        at file:///home/runner/work/XXX/node_modules/@octokit/request/dist-bundle/index.js:106:21
        at async requestWithGraphqlErrorHandling (file:///home/runner/work/XXX/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
        at async Job.doExecute (/home/runner/work/XXX/node_modules/bottleneck/light.js:405:18)
    at file:///home/runner/work/XXX/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as success] (file:///home/runner/work/XXX/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///home/runner/work/XXX/node_modules/semantic-release/index.js:218:3)
    at async Module.default (file:///home/runner/work/XXX/node_modules/semantic-release/index.js:278:22)
    at async default (file:///home/runner/work/XXX/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    RequestError [HttpError]: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID XXX. - https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits
        at file:///home/runner/work/XXX/node_modules/@octokit/request/dist-bundle/index.js:106:21
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async requestWithGraphqlErrorHandling (file:///home/runner/work/XXX/node_modules/@octokit/plugin-retry/dist-bundle/index.js:36:20)
        at async Job.doExecute (/home/runner/work/XXX/node_modules/bottleneck/light.js:405:18) {
      status: 403,
      request: [Object],
      response: [Object],
      pluginName: '@semantic-release/github'
    }
  ]
}
```

Is there anything I can do to fix this? I've tried releasing a new version after having waited 10min, but I faced the same issue.
Many thanks for your work and your help :)

### PR DESCRIPTION
**Pull request by babblebey**
This Pull request replaces the usage of the troublesome 😉 GitHub SearchAPI as primary logic in the `findSRIssue` with graphql. It relegates the searchAPI consumption to a fallback logic that will be removed in a future release.

The GraphQL functionality performs its search for Semantic Release Issue by querying for Issues on a repository with specific filter, in our case we use a `label` in the filter. This means that the PR introduces changes to the way we "create" and "find" Sematic Release issues in the `fail` and `success` script.

**Changes Made:**

- Introduced an opinionated label for Semantic Release failing release issues in form of a constant `RELEASE_FAIL_LABEL`
- Concatenated the `RELEASE_FAIL_LABEL` to the `label` param on creation of semantic release failing issue in the `fail` script; this means the our opinionated label gets added to the failing release issue regardless of the plugin `context.label` configuration value (which is either `semantic-release`, `CUSTOM_LABEL` or `false`)
    
    ```js
    const newIssue = {
      owner,
      repo,
      title: failTitle,
      body: `${body}\n\n${ISSUE_ID}`,
      labels: (labels || []).concat([RELEASE_FAIL_LABEL]), // 👈 👈 👈 👈  HERE
      assignees,
    };
    ```
- Introduced the GraphQL Query that the appropriated `filter` and passed into it is the `labels` filter with `context.label` configuration concatenated with our opinionated `RELEASE_FAIL_LABEL` as value;

    ```js
    const {
      repository: {
        issues: { nodes: issueNodes },
      },
    } = await octokit.graphql(loadGetSRIssuesQuery, {
      owner,
      repo,
      filter: {
        labels: (labels || []).concat([RELEASE_FAIL_LABEL]), // 👈 👈 👈 👈  HERE
      },
    });
    ```
- Introduced error handling to the relegated GitHub searchAPI consumption; this allows for non-stop flow of step when an error occurs in the request to the hectic 😆 endpoint  
- Converted (as initially said) GitHub searchAPI consumption to fallback logic which triggers when no fail issue is found through newly established means of finding fail issues
- Introduced the opinionated `RELEASE_FAIL_LABEL` to the failing release issues at creation as imperative label (no customizability)

### Related Issue

Fixes #867

### Screencast

**DEMO: Closing all Opened Semantic Release Issues (with `semantic-release` label, `RELEASE_FAIL_LABEL` opinionated label and without any label)**

https://github.com/user-attachments/assets/a3a09773-6f92-4e36-83c1-f28ca5315948

### CODE REVIEW

**Review by babblebey — COMMENTED** [review]
### BLOCKED HERE! HELP 🫨 📣 

Everything works just as expected giving the PR a whirl.... But in the integration test coverage; the case below is bloody frustrating me 😭 

https://github.com/semantic-release/github/blob/50c3f9ce87337f435b35d67e752862077af23de9/test/integration.test.js#L641-L996

**Here's what I've got:**

In the context of this particular test case, I have only made 2 changes, and they're stated below...

- Introduced a graphql request mock to intercept the graphql request in `findSRIssues`; did this with a function `matcher` option ensuring no conflict with the existing graphql request mock for fetching `associatedPRs`

    ```js
    .postOnce(
      // Matcher Starts
      (_, { body }) => {
        t.regex(JSON.parse(body).query, /query getSRIssues\(/);
        return true;
      },
      // Matcher Ends
      {
        data: {
          repository: {
            issues: { nodes: [] },
          },
        },
      },
    )
    ```

- THE SECOND CHANGE DYNAMICS: This change introduced different `matcher` to the `associatedPRs` graphql request mock and it leads to different errors based on the different matcher, state below...

    ```js
    .postOnce(/MATCHER_HERE/, {
      data: {
        repository: {
          commit123: {
            oid: "123",
            associatedPullRequests: {
              pageInfo: {
                endCursor: "NI",
                hasNextPage: false,
              },
              nodes: [prs[0]],
            },
          },
        },
      },
    })
    ```
  - When matcher is plain old `"https://api.github.local/graphql"` (currently commited change); See current full error at https://github.com/semantic-release/github/actions/runs/10619388030/job/29436858061?pr=907#step:8:94 or see snippet below

        ```
        [test:integration]   HttpError (RequestError) {
        [test:integration]     cause: SyntaxError {
        [test:integration]       message: '"undefined" is not valid JSON',
        [test:integration]     },
        [test:integration]     request: {
        [test:integration]       body: {
        [test:integration]         body: 'Test release note body',
        [test:integration]         draft: true,
        [test:integration]         name: 'v1.0.0',
        [test:integration]         prerelease: false,
        [test:integration]         tag_name: 'v1.0.0',
        [test:integration]       },
        [test:integration]       headers: {
        [test:integration]         accept: 'application/vnd.github.v3+json',
        [test:integration]         authorization: 'token [REDACTED]',
        [test:integration]         'content-type': 'application/json; charset=utf-8',
        [test:integration]         'user-agent': 'test octokit-core.js/6.1.2 Node.js/20.9.0 (win32; x64)',
        [test:integration]       },
        [test:integration]       method: 'POST',
        [test:integration]       request: {
        [test:integration]         agent: undefined,
        [test:integration]         fetch: Function fetchMockProxy { … },
        [test:integration]         hook: Function bound bound register {},
        [test:integration]       },
        [test:integration]       url: 'https://api.github.local/repos/test_user/test_repo/releases',
        [test:integration]     },
        [test:integration]    
        ```
  - When matcher uses a function as seen below (this set-up similar to the matcher used in the mock request for `findSRIssue` uses digs into the request object an matches to intercepts request where `query getAssociatedPRs` string is present in the query property)
    ```js
    (_, { body }) => {
      t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
      return true;
    },
    ```

    Error:
    
    ```
    [test:integration]    685:     .postOnce((_, { body }) => {
    [test:integration]    686:       t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
    [test:integration]    687:       return true;
    [test:integration]
    [test:integration]   `t.regex()` must be called with a string
    [test:integration]
    [test:integration]   Called with:
    [test:integration]
    [test:integration]   undefined
    ```
  - When matcher uses same function and asserts the request url, seen below
    ```js
    (url, { body }) => {
      t.is(url, "https://api.github.local/graphql");
      t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
      return true;
    }
    ```

    Error:
    
    ```
    [test:integration]    685:     .postOnce((url, { body }) => {
    [test:integration]    686:       t.is(url, "https://api.github.local/graphql");
    [test:integration]    687:       t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
    [test:integration]
    [test:integration]   Difference (- actual, + expected):
    [test:integration]
    [test:integration]   - 'https://api.github.local/repos/test_user/test_repo/releases'
    [test:integration]   + 'https://api.github.local/graphql'
    ```
  - When matcher uses another supported function format, seen below
    ```js
    (_, __, { body }) => {
      t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
      return true;
    }
    ``` 
    
    Error:
    
    ```
    [test:integration]   HttpError (RequestError) {
    [test:integration]     cause: TypeError {
    [test:integration]       message: 'Cannot destructure property \'body\' of \'undefined\' as it is undefined.',
    [test:integration]     },
    [test:integration]     request: {
    [test:integration]       body: {
    [test:integration]         body: 'Test release note body',
    [test:integration]         draft: true,
    [test:integration]         name: 'v1.0.0',
    [test:integration]         prerelease: false,
    [test:integration]         tag_name: 'v1.0.0',
    [test:integration]       },
    [test:integration]       headers: {
    [test:integration]         accept: 'application/vnd.github.v3+json',
    [test:integration]         authorization: 'token [REDACTED]',
    [test:integration]         'content-type': 'application/json; charset=utf-8',
    [test:integration]         'user-agent': 'test octokit-core.js/6.1.2 Node.js/20.9.0 (win32; x64)',
    [test:integration]       },
    [test:integration]       method: 'POST',
    [test:integration]       request: {
    [test:integration]         agent: undefined,
    [test:integration]         fetch: Function fetchMockProxy { … },
    [test:integration]         hook: Function bound bound register {},
    [test:integration]       },
    [test:integration]       url: 'https://api.github.local/repos/test_user/test_repo/releases',
    [test:integration]     },
    [test:integration]     response: undefined,
    [test:integration]     status: 500,
    [test:integration]     message: 'Cannot destructure property \'body\' of \'undefined\' as it is undefined.',
    [test:integration]   }
    ```

### Important Note

Delete the test case `"Verify, release and notify success"` itself and every other 242 tests are passes.... I'm very convinced something is messed up in there that I need to figure out 😢 

Cc @gr2m @travi

**Comment by babblebey** [comment]
> ### BLOCKED HERE! HELP 🫨 📣
> Everything works just as expected giving the PR a whirl.... But in the integration test coverage; the case below is bloody frustrating me 😭

Yoooooo, I addressed it 🥳🥳🥳🥳 

### What I did 🤌 

Its important to note that in my function matchers, I implemented assertion as seen below....

```js
(url, { body }) => {
  t.is(url, "https://api.github.local/graphql");
  t.regex(JSON.parse(body).query, /query getAssociatedPRs\(/);
  return true;
}
```

...well this works in some test cases and doesn't work in this particular troublesome case... But on a quick call with @gr2m today, I learnt I could/should just do away with assertions in the matchers... Hence I implement plain condition that return `true` when it finds a match for the mock... see below

```js
(url, { body }) =>
  url === "https://api.github.local/graphql" &&
  JSON.parse(body).query.includes("query getAssociatedPRs("),
```

...and voila, the bad boy works 😁.

I was also experiencing similar troubles in #874 and all in now well 😉... I guess I can have a good weekend now 😃

File: lib/definitions/constants.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
 export const ISSUE_ID = "<!-- semantic-release:github -->";
 
 export const RELEASE_NAME = "GitHub release";
+
+export const RELEASE_FAIL_LABEL = "release-failing";
```
Comment (babblebey) [inline lib/definitions/constants.js:5]:
```suggestion
export const RELEASE_FAIL_LABEL = "semantic-release";
```

File: lib/resolve-config.js [hunk 2]
```diff
@@ -38,6 +38,7 @@ export default function resolveConfig(
       : failTitle,
     failComment,
     failCommentCondition,
+    // ATTN??? We opinionated :(???
     labels: isNil(labels)
       ? ["semantic-release"]
       : labels === false
```
[the remark this answers is not in the document]
Comment (babblebey) [reply lib/resolve-config.js:44]: So.... Regardless of configured label... We will be adding the `semantic-release` label at failure Issue creation by concatenating with already label.

We are taking the route of concatenating to avoid breaking change

File: lib/resolve-config.js [hunk 3]
```diff
@@ -38,6 +38,7 @@ export default function resolveConfig(
       : failTitle,
     failComment,
     failCommentCondition,
+    // ATTN??? We opinionated :(???
```
Comment (babblebey) [inline lib/resolve-config.js:41]:
```suggestion

```

**Review by gr2m — APPROVED** [review]
Let's gooo! We discussed this extensively and @babblebey tested it locally, time to ship 🚀

**Comment by zachspar** [comment]
@babblebey the issue no longer fails my pipeline 👍, but is it using GraphQL to do the search? For my own understanding could you please elaborate on what's going on under the hood? Why is it still using GH SearchAPI at all? Thanks in advance!
```
  Request quota exhausted for request GET /search/issues
  Request quota exhausted for request GET /search/issues
  Request quota exhausted for request GET /search/issues
  Request quota exhausted for request GET /search/issues
  Request quota exhausted for request GET /search/issues
  2024-09-24T16:49:06.750Z semantic-release:github found semantic-release issues: []
  [4:49:06 PM] [semantic-release] › ℹ  An error occured fetching issue via fallback (with GH SearchAPI)
```

**Comment by babblebey** [comment]
Hey @zachspar,

Great question. The SearchAPI was used to search "semantic-release fail issue" using just the `title`, its a little different from how we are now searching with GraphQL which searches list of issues on a repo using `labels`... In order to enable empower this label search it meant that we had to change how we create the "semantic-release fail issue" in the first place, we did this by enforcing addition of an opinionated `RELEASE_FAIL_LABEL` which we will always filter with at search.

The need for SearchAPI has fallback arises in cases when their are "semantic-release fail issue" created by the old setup (these are issues that didn't get the opinionated `RELEASE_FAIL_LABEL` added at creation), so this fallback only triggers to ensure that these old issues are still caught if they exist.

**Comment by zachspar** [comment]
> The need for SearchAPI has fallback arises in cases when their are "semantic-release fail issue" created by the old setup (these are issues that didn't get the opinionated RELEASE_FAIL_LABEL added at creation), so this fallback only triggers to ensure that these old issues are still caught if they exist.

Gotcha, so it is for backward compatibility. Will there be any plans to deprecate the fallback logic? Or is there a mechanism it could use to search for these issues using GraphQL without labels?

**Comment by babblebey** [comment]
>  Will there be any plans to deprecate the fallback logic? 

Says in there 😉 

https://github.com/semantic-release/github/blob/b6ed55ed8636b492854bec5dabbe01ab3ef73feb/lib/find-sr-issues.js#L21-L24

> Or is there a mechanism it could use to search for these issues using GraphQL without labels?

None at the moment, but if we do find any GraphQL means that works as simply as we used the SearchAPI with `title`... that would be great and would mean we can completely deprecate usage of the SearchAPI.
